version: '2'
services:
 vulnerable-mysql:
  image: mysql:5.7
  container_name: vulnerable-mysql
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=root
 vulnerable-tomcat:
  image: vulnerable-tomcat
  container_name: vulnerable-tomcat
  depends_on:
    - vulnerable-mysql
  ports:
    - "8080:8080"
