apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  name: web-ingress
  namespace: jvl
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: jvl
          servicePort: 8080
        path: /*
