apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: jvl
  name: jvl
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: jvl
  type: ClusterIP
status:
  loadBalancer: {}
