apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  creationTimestamp: null
  labels:
    run: jvl
  name: jvl
=======
  labels:
    run: jvl
  name: jvl
  namespace: jvl
>>>>>>> 1b818280be5dd6bcbc3c1166f792a3431da0058d
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: jvl
<<<<<<< HEAD
  type: ClusterIP
status:
  loadBalancer: {}
=======
  sessionAffinity: None
  type: ClusterIP
>>>>>>> 1b818280be5dd6bcbc3c1166f792a3431da0058d
