apiVersion: v1
kind: Service
metadata:
  labels:
    run: jvl
  name: jvl
  namespace: jvl
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: jvl
  sessionAffinity: None
  type: ClusterIP
